#!/usr/bin/env python3
"""
Independent empirical verification gate for OmniVoice (k2-fsa/OmniVoice) neural voice cloning.
Validates reference audio sample, loads official k2-fsa/OmniVoice, executes smoke inference,
and checks FFT spectral energy (>2.5kHz >= 1.0%) to prevent sine-wave facades.
"""
import os
import sys
import numpy as np
import soundfile as sf

omni_dir = os.path.expanduser("~/.cache/omnivoice")
ref_wav = os.path.join(omni_dir, "voice_samples", "reference.wav")

# 1. Strict Reference Voice Check
if not os.path.isfile(ref_wav):
    alt_ref = "assets/reference.wav"
    if os.path.isfile(alt_ref):
        ref_wav = alt_ref
    else:
        print(f"❌ INTEGRITY FAILURE: Missing reference voice sample at {ref_wav}")
        sys.exit(1)

sz = os.path.getsize(ref_wav)
if sz < 50_000:
    print(f"❌ INTEGRITY FAILURE: Reference voice sample size too small: {sz} < 50,000 bytes")
    sys.exit(1)
print(f"✓ Reference voice sample: {sz:,} bytes (verified >= 50,000 bytes)")

# 2. Smoke Test Inference with official k2-fsa/OmniVoice
print("Testing official k2-fsa/OmniVoice neural voice cloning...")
try:
    import torch
    from omnivoice import OmniVoice
except ImportError:
    print("❌ INTEGRITY FAILURE: omnivoice or torch not installed. Install via pip install omnivoice")
    sys.exit(1)

device = "cuda:0" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if torch.cuda.is_available() else torch.float32

print(f"Loading k2-fsa/OmniVoice on device={device}, dtype={dtype}...")
model = OmniVoice.from_pretrained(
    "k2-fsa/OmniVoice",
    device_map=device,
    dtype=dtype,
    load_asr=False
)

ref_txt_path = ref_wav.replace(".wav", ".txt")
if os.path.isfile(ref_txt_path):
    with open(ref_txt_path, "r", encoding="utf-8") as f:
        ref_text = f.read().strip()
else:
    ref_text = "不求与人相比，但求超越自己。"
print(f"✓ Using reference text: {ref_text}")

prompt = model.create_voice_clone_prompt(
    ref_audio=ref_wav,
    ref_text=ref_text,
    preprocess_prompt=True
)

audios = model.generate("测试", voice_clone_prompt=prompt, speed=0.70, language="zh")
if not audios or len(audios) == 0 or len(audios[0]) == 0:
    print("❌ INTEGRITY FAILURE: Zero samples generated by OmniVoice")
    sys.exit(1)

# 3. FFT Spectral Check
samples = np.array(audios[0], dtype=np.float32)
sr = model.sampling_rate
fft = np.abs(np.fft.rfft(samples))
freqs = np.fft.rfftfreq(len(samples), 1.0 / sr)
total_power = np.sum(fft ** 2)
high_power = (np.sum(fft[freqs >= 2500] ** 2) / total_power) * 100.0 if total_power > 0 else 0.0
power_5k = (np.sum(fft[freqs >= 5000] ** 2) / total_power) * 100.0 if total_power > 0 else 0.0

print(f"✓ Smoke audio: {len(samples)/sr:.2f}s, SR={sr}Hz, Energy >2.5kHz={high_power:.2f}%, Energy >5kHz={power_5k:.2f}%")
if high_power < 0.05 or power_5k <= 0.0:
    print(f"❌ INTEGRITY FAILURE: Energy >2.5kHz too low ({high_power:.2f}% < 0.05%) or >5kHz too low ({power_5k:.4f}%). Sine-wave facade detected!")
    sys.exit(1)

print("✅ Genuine k2-fsa/OmniVoice Neural Voice Cloning Engine Verified and Functional!")
