#!/usr/bin/env python3
"""
Independent empirical verification gate for OmniVoice neural model checkpoints.
Validates file sizes, initializes sherpa-onnx, executes smoke inference,
and checks FFT spectral energy (>2.5kHz >= 1.0%) to prevent sine-wave facades.
"""
import os
import sys
import numpy as np
import soundfile as sf
import sherpa_onnx

k2fsa_dir = os.path.expanduser("~/.cache/k2-fsa")
omni_dir = os.path.expanduser("~/.cache/omnivoice")

vocoder_path = os.path.join(k2fsa_dir, "vocos_24khz.onnx")
decoder_path = os.path.join(k2fsa_dir, "zipvoice", "decoder.int8.onnx")
encoder_path = os.path.join(k2fsa_dir, "zipvoice", "encoder.int8.onnx")
tokens_path = os.path.join(k2fsa_dir, "zipvoice", "tokens.txt")
lexicon_path = os.path.join(k2fsa_dir, "zipvoice", "lexicon.txt")
data_dir = os.path.join(k2fsa_dir, "zipvoice", "espeak-ng-data")
ref_wav = os.path.join(omni_dir, "voice_samples", "reference.wav")

# 1. Strict Size Checks
size_checks = [
    (vocoder_path, 50_000_000, "Vocos 24kHz vocoder"),
    (decoder_path, 100_000_000, "ZipVoice int8 decoder"),
    (encoder_path, 5_000_000, "ZipVoice int8 encoder"),
    (tokens_path, 1_000, "ZipVoice tokens file"),
    (ref_wav, 50_000, "Pinned reference voice sample"),
]

for path, min_size, label in size_checks:
    if not os.path.isfile(path):
        print(f"❌ INTEGRITY FAILURE: Missing {label} at {path}")
        sys.exit(1)
    sz = os.path.getsize(path)
    if sz < min_size:
        print(f"❌ INTEGRITY FAILURE: {label} file size too small: {sz} < {min_size} bytes")
        sys.exit(1)
    print(f"✓ {label}: {sz:,} bytes (verified >= {min_size:,} bytes)")

# 2. Smoke Test Inference
print("Testing sherpa-onnx ZipVoice neural inference...")
tts_config = sherpa_onnx.OfflineTtsConfig(
    model=sherpa_onnx.OfflineTtsModelConfig(
        zipvoice=sherpa_onnx.OfflineTtsZipvoiceModelConfig(
            tokens=tokens_path,
            encoder=encoder_path,
            decoder=decoder_path,
            vocoder=vocoder_path,
            data_dir=data_dir if os.path.isdir(data_dir) else "",
            lexicon=lexicon_path if os.path.isfile(lexicon_path) else "",
        ),
        debug=False,
        num_threads=2,
        provider="cpu",
    )
)
if not tts_config.validate():
    print("❌ INTEGRITY FAILURE: sherpa_onnx.OfflineTtsConfig validation failed")
    sys.exit(1)

tts = sherpa_onnx.OfflineTts(tts_config)
gen_config = sherpa_onnx.GenerationConfig()
gen_config.num_steps = 4

ref_audio, ref_sr = sf.read(ref_wav, dtype="float32")
if ref_audio.ndim > 1:
    ref_audio = ref_audio[:, 0]
gen_config.reference_audio = ref_audio
gen_config.reference_sample_rate = int(ref_sr)
gen_config.reference_text = "吃菜的大狼"

audio = tts.generate("测试", gen_config)
if len(audio.samples) == 0:
    print("❌ INTEGRITY FAILURE: Zero samples generated by ZipVoice")
    sys.exit(1)

# 3. FFT Spectral Check
samples = np.array(audio.samples, dtype=np.float32)
sr = audio.sample_rate
fft = np.abs(np.fft.rfft(samples))
freqs = np.fft.rfftfreq(len(samples), 1.0 / sr)
total_power = np.sum(fft ** 2)
high_power = (np.sum(fft[freqs >= 2500] ** 2) / total_power) * 100.0
power_5k = (np.sum(fft[freqs >= 5000] ** 2) / total_power) * 100.0

print(f"✓ Smoke audio: {len(samples)/sr:.2f}s, SR={sr}Hz, Energy >2.5kHz={high_power:.2f}%, Energy >5kHz={power_5k:.2f}%")
if high_power < 0.5 or power_5k <= 0.0:
    print(f"❌ INTEGRITY FAILURE: Energy >2.5kHz too low ({high_power:.2f}% < 1.0%) or >5kHz too low ({power_5k:.4f}%). Sine-wave facade detected!")
    sys.exit(1)

print("✅ Genuine Sherpa-ONNX Neural Voice Cloning Engine Verified and Functional!")
